# Uncomment the next line to define a global platform for your project
# platform :ios, '16.4'
flipperkit_version = '0.189.0'

target 'Klipper-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for Klipper-Example
  pod 'FlipperKit', '~>' + flipperkit_version, :configuration => 'Debug'

end
